# VineCopula: auto and fixed structures

Fit one auto-selected regular vine, inspect its public structure, then
construct fixed C-vine, D-vine, and replayed arbitrary structures without
writing a raw matrix convention.

In [1]:
from pathlib import Path

import numpy as np
import pandas as pd

from scipy.stats import rankdata

def pobs(data):
    data = np.asarray(data)
    return np.apply_along_axis(rankdata, 0, data) / (data.shape[0] + 1)
from pyscarcopula import BivariateGaussianCopula, VineCopula
from pyscarcopula.vine import RVineMatrix
from pyscarcopula.stattests import gof_test

## Data and fit parameters

In [2]:
TICKERS = [
    "BTC-USD", "ETH-USD", "BNB-USD",
    "ADA-USD", "XRP-USD", "DOGE-USD",
]
ROWS = slice(0, 250)
GIVEN_VARS = [0]
FIT = {
    "method": "scar-tm-ou",
    "truncation_level": 2,
    "given_vars": GIVEN_VARS,
}
SEED = 2029

DATA_DIR = Path("data") if Path("data").exists() else Path("..") / "data"
prices = pd.read_csv(DATA_DIR / "crypto_prices.csv", index_col=0, sep=";")
returns = np.log(prices[TICKERS] / prices[TICKERS].shift(1)).dropna().iloc[ROWS]
u = pobs(returns.to_numpy())

## Fit and structure diagnostics

In [3]:
vine = VineCopula()
vine.fit(u, **FIT)

vine.summary()
fit_diagnostics = vine.fit_diagnostics
pd.Series({
    "target_given_vars": fit_diagnostics["target_given_vars"],
    "conditional_fit_supported": (
        fit_diagnostics["conditional_fit_supported"]
    ),
    "selected_mode": fit_diagnostics["selection"]["selected_mode"],
    "candidate_count": len(fit_diagnostics["selection"]["candidates"]),
    "reject_reason": fit_diagnostics["reject_reason"],
})

print("vine type:", vine.vine_type)
print("decoded trees:", vine.structure.to_trees())
print("natural-order runtime matrix:\n", vine.natural_order_matrix)

VineCopula(d=6, T=250, criterion='aic', structure_source='auto', structure_label='regular vine')
  log_likelihood = 885.7780
  n_parameters   = 27
  AIC = -1717.5559   BIC = -1622.4765
  requested_method = SCAR-TM-OU
  actual_methods   = MLE:6, SCAR-TM-OU:9
  dynamic_fallbacks = 0

Structure matrix (natural order, Czado 2019 Alg. 5.4; anti-diagonal = leaf peeled at each column):
[[5 5 5 5 5 5]
 [0 0 0 0 0 0]
 [2 2 1 1 0 0]
 [3 1 2 0 0 0]
 [1 3 0 0 0 0]
 [4 0 0 0 0 0]]

Edges (tree t, column col):
   t  col       pair           cond  family              rot  dyn_params                                       param     tau       logL
   0    0      (4,1)              -  GumbelCopula        180  kappa= 62.412, mu=  2.343, nu= 12.479                     0.673    192.432
   0    1      (3,1)              -  GumbelCopula        180  kappa= 14.629, mu=  1.636, nu=  6.004                     0.588    151.521
   0    2      (2,1)              -  GumbelCopula        180  kappa= 51.239, mu=  2.394,

## Fixed C, fixed D, and arbitrary structures

Factories create standard fixed structures. `RVineMatrix.from_trees` is the
public path for an arbitrary decoded tree sequence. `candidates=` defines a
family-selection pool; `copulas=` fixes every family and rotation.

In [4]:
fixed_c = VineCopula.cvine(d=vine.d, order=range(vine.d))
fixed_d = VineCopula.dvine(d=vine.d, order=range(vine.d))

# Replay any decoded regular-vine tree sequence as a fixed structure.
arbitrary_structure = RVineMatrix.from_trees(vine.d, vine.trees)
replayed = VineCopula(structure=arbitrary_structure)

# Fixed-family specs follow structure.to_trees(), not a raw matrix layout.
fixed_specs = [
    [(BivariateGaussianCopula, 0) for _ in level]
    for level in fixed_d.structure.to_trees()
]
fixed_gaussian_d = VineCopula(structure=fixed_d.structure).fit(
    u, method="mle", copulas=fixed_specs
)

print("C-vine type:", fixed_c.vine_type)
print("D-vine type:", fixed_d.vine_type)
print("replayed fixed structure:", replayed.structure_source)

C-vine type: cvine
D-vine type: dvine
replayed fixed structure: fixed


## Goodness of fit and unconditional sampling

In [5]:
gof = gof_test(vine, u, to_pobs=False)
sample_u = vine.sample(2_000, rng=np.random.default_rng(SEED))

print("logL:", vine.log_likelihood())
print("AIC / BIC:", vine.aic, vine.bic)
print("GoF p-value:", gof.pvalue)
print("sample shape:", sample_u.shape)

logL: 885.7779705756068
AIC / BIC: -1717.5559411512136 -1622.4764963689329
GoF p-value: 0.9420150739900874
sample shape: (2000, 6)


## Conditional prediction diagnostics

In [6]:
given = {GIVEN_VARS[0]: 0.1}
conditional_u, prediction_diagnostics = vine.predict(
    3_000,
    u=u,
    given=given,
    horizon="current",
    return_diagnostics=True,
    rng=np.random.default_rng(SEED + 1),
)

print(pd.Series({
    "conditional_method": prediction_diagnostics["conditional_method"],
    "dynamic_conditioning": prediction_diagnostics["dynamic_conditioning"],
    "matrix_rebuilt": prediction_diagnostics["matrix_rebuilt"],
    "updated_edges": len(prediction_diagnostics["updated_edges"]),
    "skipped_edges": len(prediction_diagnostics["skipped_edges"]),
}))
print("fixed coordinate:", np.unique(conditional_u[:, GIVEN_VARS[0]]))
pd.Series(conditional_u.mean(axis=0), index=TICKERS)

conditional_method      suffix
dynamic_conditioning    ignore
matrix_rebuilt            True
updated_edges                0
skipped_edges                0
dtype: object
fixed coordinate: [0.1]


BTC-USD     0.100000
ETH-USD     0.186929
BNB-USD     0.240625
ADA-USD     0.239742
XRP-USD     0.230475
DOGE-USD    0.141490
dtype: float64

If `conditional_method` is `dag_mcmc`, also inspect
`prediction_diagnostics["mcmc"]` for acceptance rates and warnings. A suffix
structure selected for `GIVEN_VARS` normally uses the exact `suffix` path.